version: "3.8"

services:
  db:
    # Постоянная перезагрузка контейнера. Даже в случае остановки или рестарта ОС
    restart: always
    privileged: true
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    volumes:
      - mvp_postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.prod.env
    expose:
      - 5432
    # Решение проблемы когда бэкенд запускается раньше чем БД
    healthcheck:
      # Не забыть корректно указать БД и пользователя!
      test: [ "CMD-SHELL", "pg_isready -d mvp_api_for_blog -U admin" ]
      interval: 3s
      timeout: 3s
      retries: 9
  backend:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile.app.prod
      args:
        HOME: /home/app
        APP_HOME: /home/app/backend
        STATIC_FILES: /home/app/backend/staticfiles
        MEDIA_FILES: /home/app/backend/mediafiles
        UPLOAD_IMAGES: /home/app/backend/mediafiles/upload_images
    volumes:
      - static:/home/app/backend/static
      - mvp_static_volume:/home/app/backend/staticfiles
      - mvp_media_volume:/home/app/backend/mediafiles
    # Зависимость от сервиса db - где запущен PostgreSQL
    depends_on:
      - db
    expose:
      - 3333
    env_file:
      - ./.prod.env
## Тут Nginx - балансировщик нагрузки для обработки множества запросов на сервер
  nginx:
    restart: always
    build:
      context: ./
      dockerfile: docker/nginx/Dockerfile.nginx
    depends_on:
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/etc/nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./app/staticfiles:/home/app/backend/staticfiles
      - mvp_static_volume:/home/app/backend/staticfiles
      - mvp_media_volume:/home/app/backend/mediafiles

volumes:
  mvp_postgres_data:
    name: mvp_postgres_data
  static:
  mvp_static_volume:
    name: mvp_static_volume
  mvp_media_volume:
    name: mvp_media_volume
